name_max: 20
email_max: 255
pass_min: 6
user_per_page: 10
paginate:
  per_page: 9
admin_layout: "admin"
app_layout: "application"
category_max: 30
description_max: 200
user_per_page: 10
cate_per_page: 10
category_max: 30
user_per_page: 10
product_per_page: 10
average_total: 0
page: 1
max_image_size: 1
cart_size: 1
min_size: 0
image:
  size: "50x50"
product_title:
  length: 15
description:
  length: 20
quantity:
  default: 1
  zero: 0
rating:
  point: !ruby/range 1..5
